export const billboardHits = [
  {
    year: 1940,
    title: "I'll Never Smile Again",
    artist: "Tommy Dorsey and His Orchestra (featuring Frank Sinatra)",
    genre: "Big Band/Jazz",
  },
  {
    year: 1941,
    title: "Chattanooga Choo Choo",
    artist: "Glenn Miller and His Orchestra",
    genre: "Big Band/Jazz",
  },

  {
    year: 1942,
    title: "White Christmas",
    artist: "Bing Crosby",
    genre: "Traditional Pop",
  },

  {
    year: 1943,
    title: "Swinging on a Star",
    artist: "Bing Crosby",
    genre: "Traditional Pop",
  },

  {
    year: 1944,
    title: "I'll Be Seeing You",
    artist: "Bing Crosby",
    genre: "Traditional Pop",
  },

  {
    year: 1945,
    title: "It's Been a Long, Long Time",
    artist: "Harry James and His Orchestra (featuring Kitty Kallen)",
    genre: "Traditional Pop",
  },

  {
    year: 1946,
    title: "The Boogie Woogie Bugle Boy",
    artist: "The Andrews Sisters",
    genre: "Swing",
  },

  {
    year: 1947,
    title: "Near You",
    artist: "Francis Craig and His Orchestra",
    genre: "Traditional Pop",
  },

  {
    year: 1948,
    title: "If You Knew Susie (Like I Know Susie)",
    artist: "Bing Crosby",
    genre: "Traditional Pop",
  },

  {
    year: 1949,
    title: "A Tree in the Meadow",
    artist: "Margaret Whiting",
    genre: "Traditional Pop",
  },

  {
    year: 1950,
    title: "The Tennessee Waltz",
    artist: "Patti Page",
    genre: "Traditional Pop",
  },

  {
    year: 1951,
    title: "Too Young",
    artist: "Nat King Cole",
    genre: "Traditional Pop",
  },
  {
    year: 1952,
    title: "Blueberry Hill",
    artist: "Fats Domino",
    genre: "Rhythm and Blues",
  },
  {
    year: 1953,
    title: "The Song from Moulin Rouge",
    artist: "Percy Faith and His Orchestra",
    genre: "Traditional Pop",
  },
  {
    year: 1954,
    title: "Little Things Mean a Lot",
    artist: "Kit Carson",
    genre: "Traditional Pop",
  },
  {
    year: 1955,
    title: "Cherry Pink and Apple Blossom White",
    artist: "Pérez Prado",
    genre: "Latin/Jazz",
  },
  {
    year: 1956,
    title: "Heartbreak Hotel",
    artist: "Elvis Presley",
    genre: "Rock and Roll",
  },
  {
    year: 1957,
    title: "All Shook Up",
    artist: "Elvis Presley",
    genre: "Rock and Roll",
  },
  {
    year: 1958,
    title: "Volare (Nel blu dipinto di blu)",
    artist: "Domenico Modugno",
    genre: "Traditional Pop",
  },
  {
    year: 1959,
    title: "A Big Hunk O' Love",
    artist: "Elvis Presley",
    genre: "Rock and Roll",
  },
  {
    year: 1960,
    title: "Theme from A Summer Place",
    artist: "Percy Faith and His Orchestra",
    genre: "Easy Listening",
  },
  {
    year: 1961,
    title: "Tossin' and Turnin'",
    artist: "Bobby Lewis",
    genre: "Rock and Roll",
  },
  {
    year: 1962,
    title: "Billy Don't Be a Hero",
    artist: "Bo Donaldson and The Heywoods",
    genre: "Pop/Rock",
  },
  {
    year: 1963,
    title: "Sugar Shack",
    artist: "Jimmy Gilmer and The Fireballs",
    genre: "Pop/Rock",
  },
  {
    year: 1964,
    title: "I Want to Hold Your Hand",
    artist: "The Beatles",
    genre: "Rock",
  },
  {
    year: 1965,
    title: "Wooly Bully",
    artist: "Sam The Sham and The Pharaohs",
    genre: "Rock",
  },
  {
    year: 1966,
    title: "Ballad of the Green Berets",
    artist: "Barry Sadler",
    genre: "Country/Pop",
  },
  { year: 1967, title: "To Sir With Love", artist: "Lulu", genre: "Pop" },
  { year: 1968, title: "Hey Jude", artist: "The Beatles", genre: "Rock" },
  {
    year: 1969,
    title: "Sugar, Sugar",
    artist: "The Archies",
    genre: "Bubblegum Pop",
  },
  {
    year: 1970,
    title: "Bridge Over Troubled Water",
    artist: "Simon & Garfunkel",
    genre: "Folk Rock",
  },
  {
    year: 1971,
    title: "Joy to the World",
    artist: "Three Dog Night",
    genre: "Rock",
  },
  {
    year: 1972,
    title: "The First Time Ever I Saw Your Face",
    artist: "Roberta Flack",
    genre: "R&B/Soul",
  },
  {
    year: 1973,
    title: "Bad, Bad Leroy Brown",
    artist: "Jim Croce",
    genre: "Rock",
  },
  {
    year: 1974,
    title: "The Way We Were",
    artist: "Barbra Streisand",
    genre: "Pop",
  },
  {
    year: 1975,
    title: "Love Will Keep Us Together",
    artist: "Captain & Tennille",
    genre: "Pop",
  },
  {
    year: 1976,
    title: "Tonight's the Night (Gonna Be Alright)",
    artist: "Rod Stewart",
    genre: "Rock",
  },
  { year: 1977, title: "Angie", artist: "The Rolling Stones", genre: "Rock" },
  { year: 1978, title: "Night Fever", artist: "Bee Gees", genre: "Disco" },
  { year: 1979, title: "My Sharona", artist: "The Knack", genre: "Rock" },
  { year: 1980, title: "Call Me", artist: "Blondie", genre: "Rock/Pop" },
  {
    year: 1981,
    title: "Bette Davis Eyes",
    artist: "Kim Carnes",
    genre: "Rock/Pop",
  },
  { year: 1982, title: "Physical", artist: "Olivia Newton-John", genre: "Pop" },
  {
    year: 1983,
    title: "Every Breath You Take",
    artist: "The Police",
    genre: "Rock/Post-Punk",
  },
  { year: 1984, title: "When Doves Cry", artist: "Prince", genre: "R&B/Pop" },
  {
    year: 1985,
    title: "We Are the World",
    artist: "USA for Africa",
    genre: "Pop",
  },
  {
    year: 1986,
    title: "Kiss",
    artist: "Prince and the Revolution",
    genre: "Rock/Funk",
  },
  {
    year: 1987,
    title: "I Wanna Dance with Somebody (Who Loves Me)",
    artist: "Whitney Houston",
    genre: "Pop",
  },
  { year: 1988, title: "Faith", artist: "George Michael", genre: "Pop/Rock" },
  { year: 1989, title: "Look Away", artist: "Chicago", genre: "Rock/Pop" },
  {
    year: 1990,
    title: "Another Day in Paradise",
    artist: "Phil Collins",
    genre: "Pop/Rock",
  },
  {
    year: 1991,
    title: "Everything I Do (I Do It for You)",
    artist: "Bryan Adams",
    genre: "Rock",
  },
  { year: 1992, title: "End of the Road", artist: "Boyz II Men", genre: "R&B" },
  {
    year: 1993,
    title: "I Will Always Love You",
    artist: "Whitney Houston",
    genre: "R&B/Pop",
  },
  { year: 1994, title: "The Sign", artist: "Ace of Base", genre: "Pop" },
  {
    year: 1995,
    title: "Gangsta's Paradise",
    artist: "Coolio (featuring L.V.)",
    genre: "Hip Hop",
  },
  {
    year: 1996,
    title: "Macarena (Bayside Boys Remix)",
    artist: "Los Del Rio",
    genre: "Latin/Pop",
  },
  {
    year: 1997,
    title: "Something About the Way You Look Tonight - Candles",
    artist: "Elton John",
    genre: "Pop",
  },
  { year: 1998, title: "Too Much", artist: "Carly Rae Jepsen", genre: "Pop" },
  { year: 1999, title: "Believe", artist: "Cher", genre: "Dance/Pop" },
  { year: 2000, title: "Breathe", artist: "Faith Hill", genre: "Country" },
  {
    year: 2001,
    title: "Hanging by a Moment",
    artist: "Lifehouse",
    genre: "Rock",
  },
  {
    year: 2002,
    title: "How You Remind Me",
    artist: "Nickelback",
    genre: "Rock",
  },
  { year: 2003, title: "In Da Club", artist: "50 Cent", genre: "Hip Hop/Rap" },
  {
    year: 2004,
    title: "Yeah!",
    artist: "Usher (featuring Lil Jon and Ludacris)",
    genre: "R&B/Hip Hop",
  },
  {
    year: 2005,
    title: "We Belong Together",
    artist: "Mariah Carey",
    genre: "R&B/Pop",
  },
  { year: 2006, title: "Bad Day", artist: "Daniel Powter", genre: "Pop/Rock" },
  { year: 2007, title: "Irreplaceable", artist: "Beyoncé", genre: "R&B/Pop" },
  {
    year: 2008,
    title: "Low",
    artist: "Flo Rida (featuring T-Pain)",
    genre: "Hip Hop/Rap",
  },
  {
    year: 2009,
    title: "Boom Boom Pow",
    artist: "The Black Eyed Peas",
    genre: "Hip Hop/Dance",
  },
  { year: 2010, title: "Tik Tok", artist: "Kesha", genre: "Pop/Dance" },
  {
    year: 2011,
    title: "Rolling in the Deep",
    artist: "Adele",
    genre: "Pop/Soul",
  },
  {
    year: 2012,
    title: "Somebody That I Used to Know",
    artist: "Gotye (featuring Kimbra)",
    genre: "Indie Pop",
  },
  {
    year: 2013,
    title: "Blurred Lines",
    artist: "Robin Thicke (featuring T.I. and Pharrell)",
    genre: "R&B/Pop",
  },
  { year: 2014, title: "Happy", artist: "Pharrell Williams", genre: "Pop" },
  {
    year: 2015,
    title: "Uptown Funk",
    artist: "Mark Ronson (featuring Bruno Mars)",
    genre: "Funk/Pop",
  },
  {
    year: 2016,
    title: "Closer",
    artist: "The Chainsmokers (featuring Halsey)",
    genre: "Dance/Pop",
  },
  { year: 2017, title: "Shape of You", artist: "Ed Sheeran", genre: "Pop" },
  {
    year: 2018,
    title: "Girls Like You",
    artist: "Maroon 5 (featuring Cardi B)",
    genre: "Pop/R&B",
  },
  {
    year: 2019,
    title: "Old Town Road",
    artist: "Lil Nas X (featuring Billy Ray Cyrus)",
    genre: "Country/Rap",
  },
  {
    year: 2020,
    title: "Blinding Lights",
    artist: "The Weeknd",
    genre: "Synthpop",
  },
  {
    year: 2021,
    title: "Stay",
    artist: "The Kid LAROI and Justin Bieber",
    genre: "Pop/Rap",
  },
  {
    year: 2022,
    title: "Heat Waves",
    artist: "Glass Animals",
    genre: "Alternative/Indie",
  },
  { year: 2023, title: "Flowers", artist: "Miley Cyrus", genre: "Pop" },
  {
    year: 2024,
    title:
      "The year 2024 is not complete, and year-end rankings for this year won't be available until later in the year.",
  },
];
